# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d582aa449cf1633f5e1aa397e6edf1b9a0ae154fa7e88cec84b67d28ac57913f73384352555704128fef5b9a67d5cdf6fc010b02789d848ff9bf335b837d477d

test:
  secret_key_base: b109555c6bf4883922f6e41781a4c1cb63e6b82f109f0e91bd047bff4bb8eb322f53e08db6b1905ac5962b36ae6ad6cb663dd8d5d3356232907702c25cdde1ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
